### PR TITLE
Setting a height for the chart, and disabling responsiveRatio

### LINKED ISSUE #26: Charts were fullwidth on previous app
Should we make them fullwidth again, or is it not really comfortable for reading ? 

It would improve size of chart considerably and make it easier to read (because lots of data inside), but it would make the page look "full of bars" and that might be soso.

To improve readness of the chart, we could also try to chop some data out of it.

### PR DESCRIPTION
**Pull request by Vin0uz**
Closes #26

Here is a preview, what do you think about this @VideoNMF 

Capture d’écran 2020-05-12 à 22 03 35

### CODE REVIEW

**Comment by VideoNMF** [comment]
I think it's better now but you are maybe right to put the two graphs side to side if de group the datas. 

What do you think about this ?

**Comment by Vin0uz** [comment]
> I think it's better now but you are maybe right to put the two graphs side to side if de group the datas.
> 
> What do you think about this ?

I will wait till we chopped the data to see how it looks with smaller data and then we compare :) this is ready anyway 😄

**Comment by Vin0uz** [comment]
Will need a big rebase after #39

**Comment by Vin0uz** [comment]
After running the update on action types, it looks like this: 
Before full width: 
image

After full width: image

**Comment by VideoNMF** [comment]
Both have their advantages :
- Before full widht is more compact and more Pleasant to see for a Dashboard
- After full widht is more visible and I think when we have 26 game of championship it will be more visible and Pleasant to see

What do you think about it ?

**Comment by Vin0uz** [comment]
> Both have their advantages :
> 
> * Before full widht is more compact and more Pleasant to see for a Dashboard
> * After full widht is more visible and I think when we have 26 game of championship it will be more visible and Pleasant to see
> 
> What do you think about it ?

As far as we don't know for sure, I propose to leave it as it is for now, and re-open this problem later if we decide that it is require. (Maybe we will go in other directions : allow people to open the chart alone in a wide popup, allow people to decide which kind of display they want etc..). 

The main thing is that we shouldn't consider "our point of view" to be the best anyway, it is better to have feedback from users and decide accordingly (but not only listen to user because they are sometimes wrong.). So far, you are the user so if both views are ok for you, we don't need to change and we can focus on something else :)

**Pull request closed without merging**
