### PR TITLE
Use doughtnuts instead of polar area

### LINKED ISSUE #25: Polar Area graph might be better as pies
Considering they are all about proportions to each other, the pie/doughnut view might be much easier to read considering there is a huge gap between max (150+) and min (15) value.

This gap between the values make it very hard to see the min one, when it might still appear better on a pie. Dunno for sure, but worth taking a quick look I believe :)

### PR DESCRIPTION
**Pull request by Vin0uz**
; Closes #25
Before : 
Capture d’écran 2020-05-12 à 22 13 06

After : 
Capture d’écran 2020-05-12 à 22 12 04

### CODE REVIEW

**Comment by Vin0uz** [comment]
Remark : It might be looking better if the borderColor were `white` : it would show separation between colors 🤔

**Comment by VideoNMF** [comment]
Yes it's better with pies 👍

Do you think it's possible to put the teams in order from largest to smallest ?

**Comment by Vin0uz** [comment]
Will need a big rebase after #39

**Comment by Vin0uz** [comment]
Demo with white border set and much "flashier" colors. On a personal note : i like it a lot better like this 😻

image

**Comment by VideoNMF** [comment]
I am ok it's better now !
"flashier colors" is a top idea ;)

**Pull request merged**
